# Pre-commit hooks configuration for Modan2
# Install: pip install pre-commit
# Setup: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Ruff - Fast Python linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Prevent committing large files
      - id: check-added-large-files
        args: [--maxkb=1000]
      # Check YAML files
      - id: check-yaml
      # Check JSON files
      - id: check-json
      # Check for files that would conflict on case-insensitive filesystems
      - id: check-case-conflict
      # Check for merge conflict strings
      - id: check-merge-conflict
      # Ensure files end with newline
      - id: end-of-file-fixer
        exclude: \.qm$|\.png$|\.jpg$|\.ico$|\.db$
      # Trim trailing whitespace
      - id: trailing-whitespace
        exclude: \.qm$|\.png$|\.jpg$|\.ico$|\.db$

  # Type checking with mypy (optional - disabled by default due to lack of type hints)
  # Uncomment when ready to enforce type checking
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.11.2
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [types-all]
  #       args: [--ignore-missing-imports, --allow-untyped-calls]

# Configuration
default_language_version:
  python: python3.12

# Skip these paths
exclude: |
  (?x)(
      ^\.index/|
      ^htmlcov/|
      ^\.pytest_cache/|
      ^build/|
      ^dist/|
      ^migrations/|
      ^OBJFileLoader/|
      \.egg-info/|
      \.qm$|
      \.png$|
      \.jpg$|
      \.ico$|
      \.db$
  )
