# Modan2 developer convenience targets.
#
# Dependency lockfiles are the source of truth for reproducible installs. They
# are PER-PLATFORM, not universal: PyQt5's Qt binary (pyqt5-qt5) ships different
# latest versions per OS — Linux/macOS reach 5.15.19 but Windows stops at
# 5.15.2 — so a single universal pin is uninstallable on Windows. One lock per
# target platform sidesteps that:
#
#   requirements-linux.lock    requirements-windows.lock    requirements-macos.lock
#
# Each is the full set (runtime + dev/test, from requirements.txt +
# config/requirements-dev.txt), hash-pinned, compiled with a 3.11 floor to
# cover the CI test matrix (Python 3.11 and 3.12). CI test and build jobs each
# install the lock matching their runner with `--require-hashes`.

# Keep the compile flags identical between `lock` and `lock-check`, or the drift
# check reports spurious diffs.
SHELL         := bash
UV            ?= uv
PY_FLOOR      ?= 3.11
PLATFORMS     := linux windows macos
SOURCES       := requirements.txt config/requirements-dev.txt
COMPILE        = $(UV) pip compile --python-version $(PY_FLOOR) --generate-hashes

.PHONY: lock lock-check

# Regenerate every per-platform lock from the requirements source files. Run
# this after editing requirements.txt or config/requirements-dev.txt, then
# commit the locks.
lock:
	@for p in $(PLATFORMS); do \
		echo "Locking $$p ..."; \
		$(COMPILE) --python-platform $$p $(SOURCES) -o requirements-$$p.lock; \
	done

# Fail if any committed lock is stale relative to the requirements files.
# Regenerates each to a temp file and diffs, ignoring the autogenerated header
# (which embeds the exact command and would otherwise always differ).
lock-check:
	@set -e; \
	for p in $(PLATFORMS); do \
		tmp=$$(mktemp); \
		$(COMPILE) --python-platform $$p $(SOURCES) -o $$tmp >/dev/null 2>&1; \
		if ! diff -q <(grep -v '^#' requirements-$$p.lock) <(grep -v '^#' $$tmp) >/dev/null; then \
			echo "requirements-$$p.lock is out of date. Run 'make lock' and commit."; \
			diff <(grep -v '^#' requirements-$$p.lock) <(grep -v '^#' $$tmp) || true; \
			rm -f $$tmp; exit 1; \
		fi; \
		rm -f $$tmp; \
	done; \
	echo "Lockfiles are up to date."
