# .github/workflows/build-windows.yml

name: Build Windows Installer

on:
  push:
    branches: [ "main" ]
  # 수동으로 직접 실행할 수도 있도록 workflow_dispatch 추가
  workflow_dispatch:

jobs:
  build:
    # 실행 환경을 최신 Windows로 지정
    runs-on: windows-latest

    steps:
      # 1. Git 저장소의 코드를 가져옵니다.
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Python 3.12 버전을 설치합니다.
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3. 필요한 파이썬 라이브러리를 설치합니다.
      - name: Install dependencies
        run: |
          pip install -r requirements_win.txt
          pip install pyinstaller

      # 4. PyInstaller로 프로그램 빌드 (--onedir 모드 권장)
      - name: Build application bundle with PyInstaller
        run: |
          python -m PyInstaller --onedir --noconsole --add-data "icons/*.png;icons" --add-data "translations/*.qm;translations" --add-data "migrations/*;migrations" --icon="icons/Modan2_2.png" Modan2.py

      # 5. Inno Setup 설치 (Marketplace Action 사용)
      - name: Set up Inno Setup
        uses: Minishlink/actions-innosetup@v1.2.0

      # 6. Inno Setup 컴파일러 실행
      - name: Compile Inno Setup installer
        run: |
          iscc.exe "InnoSetup/Modan2.iss"

      # 7. 최종 설치 파일을 artifact로 업로드 (와일드카드 사용)
      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: Modan2-Windows-Installer
          # 동적인 파일 이름을 잡기 위해 와일드카드(*)를 사용합니다.
          path: InnoSetup/Output/Modan2_v*_Installer.exe
