name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag (e.g., v0.1.4-beta.5)'
        required: true
        type: string
      prerelease:
        description: 'Is this a pre-release?'
        required: true
        type: boolean
        default: true
      release_notes:
        description: 'Release notes (optional)'
        required: false
        type: string

permissions:
  contents: write

jobs:
  call-build-workflow:
    uses: ./.github/workflows/reusable_build.yml
    with:
      build_number: ${{ github.run_number }}

  create-release:
    needs: call-build-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-files/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version_tag }}
          name: Modan2 ${{ github.event.inputs.version_tag }} (Build ${{ github.run_number }})
          body: |
            🚀 Modan2 ${{ github.event.inputs.version_tag }} Release
            
            Built from commit: ${{ github.sha }}
            Build number: ${{ github.run_number }}
            
            ${{ github.event.inputs.release_notes }}
          prerelease: ${{ github.event.inputs.prerelease }}
          files: |
            release-files/modan2-windows/Modan2-Windows-*.zip
            release-files/modan2-macos/Modan2-macOS-*.dmg
            release-files/modan2-linux/Modan2-Linux-*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}