name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  call-build-workflow:
    uses: ./.github/workflows/reusable_build.yml
    with:
      build_number: ${{ github.run_number }}

  create-release:
    needs: call-build-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-files/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Modan2 ${{ github.ref_name }}
          body: |
            🚀 Modan2 ${{ github.ref_name }} Release

            Built from commit: ${{ github.sha }}
          prerelease: ${{ contains(github.ref_name, '-alpha') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-rc') }}
          files: |
            release-files/modan2-windows/Modan2-Windows-*.zip
            release-files/modan2-macos/Modan2-macOS-*.dmg
            release-files/modan2-linux/Modan2-Linux-*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}